language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: anyoldtimebackend
  api_key:
    secure: tQ3+1Wtjt8rGww+K9GxXT1D0Jd6/NzRcC44dpK23Ez7N7Q5PlebPNldwjZ4TjXPKXs9UqnDaNWyhY3xJFvtXAk0DZnEhhW/lg956dLLTACDFRVYIKsPXMRXJBeg4r2c1+grhtjF4Kt56nr9bZuj1NzslE0vA4SOMDjf5IfGEl0aZDD/XEgFHNPXnH5YzcMWCx9SSgOuYs8M0AeQhf/Ooe+Dn5nxhfXFKh8qRL6dJGVgZSLnZebj/tc5IeFIh2OVqPuykWxNUxRbj1mEWn9NGkO/fYm82WKrjSL+p78/AMEBiwtpQCSS1xQt3Y8w7Em6f+CfZOXjJuqDn04BeJwuiab30Jn9qeW/MFllnidCKh/WpzksntjnjqEnK9t4Z9G6m9iTGA48UaVbKS6sClTAq785CT57ieEeI7gvcZ500Ljo6NgoJgVPPaAn55MFpISAE5WrmFTwmg3k3IvVHdVV571yy5VHzGY1jzN8wUb5Nygj2YtfgNzA+bHwOHna4/JbBBeb+azdZNURqoQokExFSDYh4E2oEVQRWYnhpqOAWDEmyxtWF6Uv6NlU+0iO+GYgb7DwHRtHtYM6PuP75SVKYJN8tkhayF+BfC080bUfMGQi1eLJTJvc6m+qS5nOJNX6dOoX1yjNT+GQwEsIkJhvDwvdlThwdjcoV5kwlBr90j1w=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
